# Generated by Django 4.1.3 on 2022-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('mobile', models.CharField(default='18303756676', max_length=11, verbose_name='电话')),
                ('rank', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='级别')),
            ],
        ),
    ]
