# Generated by Django 4.1.3 on 2022-11-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paperinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, verbose_name='题名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('source', models.CharField(max_length=32, verbose_name='来源')),
                ('create_time', models.DateField(verbose_name='发表时间')),
                ('filepath', models.CharField(max_length=128, verbose_name='文档')),
            ],
        ),
        migrations.DeleteModel(
            name='PaperInfo',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='paper',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo', verbose_name='上传者'),
        ),
    ]
